package Module;

public enum PlantType {
    NORMAL, ICE, PROJECTILE, DOUBLE_SHOT, TRIPLE_LINE, CACTUS, GATLING_PEA, RANGE, STOP, SPLIT, LILY_PAD, BOMB,
    EXPLDOE_NUT, DEFENCE, NEAR_HIT, MAGNET, MINE, SUNFLOWER, LINE_BOMB, ICE_PROJECTILE, TWIN_SUNFLOWER
}
